### ISSUE TITLE
can't use 'local' database through mongos

### ISSUE THREAD

**Issue by yangchunhe** [JacketWoo/mongosync#10]
terminate called after throwing an instance of 'mongo::UserException'
what():  nextSafe(): { $err: "can't use 'local' database through mongos", code: 13644 }

**Comment by yangchunhe** [comment]
./mongosync --src_srv 10.0.100.111:60000 --src_user admin --src_passwd xxxxx --src_auth_db admin --db competence  --dst_srv 10.0.100.138:60000 --dst_user admin --dst_passwd xxxxx--dst_auth_db admin --dst_db competence --bg_num 10 --oplog 
[INFO ]		monogosync started, first set log level to INFO
[INFO ]		Sep 03 20:35:51 2017	[mongosync]	connect to srv_rsv: 10.0.100.16:60000 ok!
[INFO ]		Sep 03 20:35:51 2017	[mongosync]	srv: 10.0.100.16:60000, dbname: admin ok!
[INFO ]		Sep 03 20:35:51 2017	[mongosync]	connect to srv_rsv: 10.0.100.38:60000 ok!
[INFO ]		Sep 03 20:35:51 2017	[mongosync]	srv: 10.0.100.38:60000, dbname: admin ok!
terminate called after throwing an instance of 'mongo::UserException'
  what():  nextSafe(): { $err: "can't use 'local' database through mongos", code: 13644 }

**Comment by gaodq** [comment]
现在的release版本还不支持mongos，你可以试一下[mongos](https://github.com/Qihoo360/mongosync/tree/mongos)分支

**Comment by liansghuaifan** [comment]
我也遇到了这个问题，那什么是mongos分支呀

**Comment by liansghuaifan** [comment]
大神快合一个版本吧，我这边git分支都不太会用呀

**Comment by gaodq** [comment]
https://github.com/Qihoo360/mongosync/commit/55b647e81c072ebe91daaa3b9dc1a953c3c22e19
