### ISSUE TITLE
make  error！

### ISSUE THREAD

**Issue by MikePing** [JacketWoo/mongosync#3]
scons -C ./dep/mongo-cxx-driver --ssl install -j 1
scons: Entering directory `/home/mike/mongosync/dep/mongo-cxx-driver'
scons: Reading SConscript files ...
scons version: 2.0.1
python version: 2 6 6 'final' 0
Checking whether the C++ compiler worksyes
Checking whether the C compiler worksyes
Checking if C++ compiler "g++" is GCC... yes
Checking if C compiler "gcc" is GCC... yes
Checking if C compiler supports -Wno-unused-local-typedefs... no
Checking if C compiler supports -Wno-unused-function... yes
Checking if C compiler supports -Wno-unused-private-field... no
Checking if C compiler supports -Wno-deprecated-declarations... yes
Checking if C compiler supports -Wno-tautological-constant-out-of-range-compare... no
Checking if C compiler supports -Wno-unused-const-variable... no
Checking if C compiler supports -Wno-missing-braces... yes
Checking if we are using libstdc++... yes
Checking for libstdc++ 4.6.0 or better... no
Checking if we are on a POSIX system... yes
Checking if the POSIX monotonic clock is supported... yes
Checking for __thread... no
Checking for gcc __atomic builtins... no
Checking for useable __sync builtins... no
Checking for C++ header file boost/version.hpp... yes
Checking for C++ library boost_regex-mt... no
Checking for C++ library boost_regex... no
can't find boost
make: *** [dep/mongo-cxx-driver/build/install/lib/libmongoclient.a] Error 1

**Comment by MikePing** [comment]
我已经安装了boost,但是报了这个错误！

**Comment by MikePing** [comment]
请问，mongosync 支持mongodb3.4+不？

**Comment by kingjike** [comment]
@MikePing 你这错误是mongo的c++驱动编译错误，更详细的日志位置：mongosync/dep/mongo-cxx-driver/build/scons/config.log
看这个日志

**Comment by MikePing** [comment]
file /home/mike/mongosync/dep/mongo-cxx-driver/SConstruct,line 1014:
        Configure(confdir = build/scons/sconf_temp)
scons: Configure: Checking if C++ compiler "g++" is GCC...
build/scons/sconf_temp/conftest_2.cpp <-
  |
  |#if !defined(__GNUC__) || defined(__clang__)
  |#error
  |#endif

**Comment by MikePing** [comment]
错误比较多，我先试着一个个处理，谢谢！

**Comment by raindylong** [comment]
@MikePing ，我同样在编译这里遇到相同的问题了，请问最后是怎么解决的？感谢。
`src/mongo/base/global_initializer.cpp:32:18: error: 'mongo::{anonymous}::_theGlobalInitializer' defined but not used [-Werror=unused-variable]
     Initializer* _theGlobalInitializer = &getGlobalInitializer();
                  ^
cc1plus: all warnings being treated as errors
scons: *** [build/linux2/ssl/mongo/base/global_initializer.o] Error 1
scons: building terminated because of errors.
Makefile:58: recipe for target 'dep/mongo-cxx-driver/build/install/lib/libmongoclient.a' failed
make: *** [dep/mongo-cxx-driver/build/install/lib/libmongoclient.a] Error 2`

我的编译是基于ubuntu 16.04LTS

**Comment by wavelet123** [comment]
能不能直接给一个编译好的二进制文件

**Comment by elipoke** [comment]
能不能直接给一个编译好的二进制文件

**Comment by baotiao** [comment]
我们后续会提供一个 二进制的版本

**Comment by gaodq** [comment]
https://github.com/Qihoo360/mongosync/releases/download/v1.0/mongosync.1.0.tar.bz2
@MikePing 
@wavelet123 
@elipoke 
centos6.2下编译

**Comment by elipoke** [comment]
@baotiao 
@gaodq 
谢谢

**Comment by jiangjianjian** [comment]
同问，已经yum install了boost，还是没法通过。
mongosync/dep/mongo-cxx-driver/build/scons/config.log内容如下：
g++ -o build/scons/sconf_temp/conftest_19.o -c -Wnon-virtual-dtor -Woverloaded-virtual -fPIC -ggdb -pthread -Wall -Wsign-compare -Wno-unknown-pragmas -Winvalid-pch -pipe -Werror -O3 -Wno-unused-local-typedefs -Wno-unused-function -Wno-deprecated-declarations -Wno-missing-braces -DMONGO_EXPOSE_MACROS -D_FILE_OFFSET_BITS=64 -Ibuild/linux2/ssl/third_party/gtest-1.7.0/include -Ibuild/linux2/ssl -Ibuild/linux2/ssl/mongo build/scons/sconf_temp/conftest_19.cpp
g++ -o build/scons/sconf_temp/conftest_19 -fPIC -Wl,-z,now -rdynamic -pthread build/scons/sconf_temp/conftest_19.o -L/usr/lib64 -L/lib64 -lm -lpthread -lssl -lcrypto -lboost_regex-mt
/bin/ld: cannot find -lssl
/bin/ld: cannot find -lcrypto
collect2: error: ld returned 1 exit status
scons: Configure: no

scons: Configure: Checking for C++ library boost_regex... 
build/scons/sconf_temp/conftest_20.cpp <-
  |
  |
  |
  |int
  |main() {
  |  
  |return 0;
  |}
  |
g++ -o build/scons/sconf_temp/conftest_20.o -c -Wnon-virtual-dtor -Woverloaded-virtual -fPIC -ggdb -pthread -Wall -Wsign-compare -Wno-unknown-pragmas -Winvalid-pch -pipe -Werror -O3 -Wno-unused-local-typedefs -Wno-unused-function -Wno-deprecated-declarations -Wno-missing-braces -DMONGO_EXPOSE_MACROS -D_FILE_OFFSET_BITS=64 -Ibuild/linux2/ssl/third_party/gtest-1.7.0/include -Ibuild/linux2/ssl -Ibuild/linux2/ssl/mongo build/scons/sconf_temp/conftest_20.cpp
g++ -o build/scons/sconf_temp/conftest_20 -fPIC -Wl,-z,now -rdynamic -pthread build/scons/sconf_temp/conftest_20.o -L/usr/lib64 -L/lib64 -lm -lpthread -lssl -lcrypto -lboost_regex
/bin/ld: cannot find -lssl
/bin/ld: cannot find -lcrypto
collect2: error: ld returned 1 exit status
scons: Configure: no

**Comment by gaodq** [comment]
yum install openssl-devel

**Comment by jiangjianjian** [comment]
感谢感谢，确实还需要安装openssl-devel
