### ISSUE TITLE
同步的时候直接导致 mongo 从库挂掉了

### ISSUE THREAD

**Issue by wavelet123** [JacketWoo/mongosync#4]
[INFO ]         May 16 17:38:47 2017    [mongosync]     cloning xxx.contacts to xxx.contacts
[INFO ]         May 16 17:38:47 2017    [mongosync]     cloning xxx.contacts indexes
[INFO ]         May 16 17:38:47 2017    [mongosync]     clone xxx.contacts indexes success, total 5objects

[WARN ]         exception occurs: xxx:2009910278 dbclient error communicating with server: xxx:20099, retry it
terminate called after throwing an instance of 'mongo::SocketException'
  what():  socket exception [FAILED_STATE] for xxx:20099 (xxx.31) failed

**Comment by gaodq** [comment]
连接的主库？从库有报什么吗？

**Comment by gaodq** [comment]
可能是1.0不支持slaveok，试下 #5 里面的二进制
