### ISSUE TITLE
mongosync 执行同步报错

### ISSUE THREAD

**Issue by elipoke** [JacketWoo/mongosync#5]
@baotiao 
@gaodq 
@smartOf360 
@flabby 

[root@hadoopdn-02 mongosync_1_0]# ./ mongosync --src_srv 192.168.4.24:10011 --src_user root --src_passwd xxxx --src_auth_db admin --db src --dst_db dst--dst_srv 192.168.4.32:10011 --dst_user root --dst_passwd 12345678 --dst_auth_db admin 
[INFO ]         monogosync started, first set log level to INFO
[INFO ]         May 24 17:23:20 2017    [mongosync]     connect to srv_rsv: 192.168.4.24:10011 ok!
[INFO ]         May 24 17:23:20 2017    [mongosync]     srv: 192.168.4.24:10011, dbname: admin ok!
[INFO ]         May 24 17:23:20 2017    [mongosync]     connect to srv_rsv: 192.168.4.32:10011 ok!
[INFO ]         May 24 17:23:20 2017    [mongosync]     srv: 192.168.4.32:10011, dbname: admin ok!
[INFO ]         May 24 17:23:20 2017    [mongosync]     cloning db: src----> dst

[INFO ]         May 24 17:23:20 2017    [mongosync]     cloning src.groupTest1 to dst.groupTest1
[WARN ]         exception occurs: 10278 dbclient error communicating with server: 192.168.4.24:10011, retry it
terminate called after throwing an instance of 'mongo::SocketException'
  what():  socket exception [FAILED_STATE] for 192.168.4.24:10011 (192.168.4.24) failed
Aborted (core dumped)
[root@hadoopdn-02 mongosync_1_0]# ./mongosync
[INFO ]         monogosync started, first set log level to INFO
[FATAL]         Wrong argument number
Follow is the mongosync-surpported options: 
--help                   to get the help message
-c conf.file             use config file to start mongosync
--src_srv arg            the source mongodb server's ip port
--src_user arg           the source mongodb server's logging user
--src_passwd arg         the source mongodb server's logging password
--src_auth_db arg        the source mongodb server's auth db
--src_use_mcr            force source connection to use MONGODB-CR password machenism
--dst_srv arg            the destination mongodb server's ip port
--dst_user arg           the destination mongodb server's logging user
--dst_passwd arg         the destination mongodb server's logging password
--dst_auth_db arg        the destination mongodb server's auth db
--dst_use_mcr            force destination connection to use MONGODB-CR password machenism
--db arg                 the source database to be cloned
--dst_db arg             the destination database
--coll arg               the source collection to be cloned
--dst_coll arg           the destination collection
--oplog                  whether to sync oplog
--raw_oplog              whether to only clone oplog
--op_start arg           the start timestamp to sync oplog
--op_end arg             the start timestamp to sync oplog
--dst_op_ns arg          the destination namespace for raw oplog mode
--no_index               whether to clone the db or collection corresponding index
--filter arg             the bson format string used to filter the records to be transfered
--bg_num arg             the background thread number for cloning data(not oplog syncing and oplog storing)
--batch_size arg         the data grouping size criterion in cloning data(0-16M, default to 16M), unit is Byte
--log_level arg          specify the log level
[root@hadoopdn-02 mongosync_1_0]# 

每次启动都要做一次复制集的primary选举切换，然后 就报错了，有遇到过吗？什么问题

**Comment by gaodq** [comment]
应该是这个release版本不支持slave ok，试下这个
[mongosync_f650c8f.zip](https://github.com/Qihoo360/mongosync/files/1025243/mongosync_f650c8f.zip)

**Comment by elipoke** [comment]
@gaodq 
1.0版本不支持mongos-mongos的全量和增量同步？

**Comment by elipoke** [comment]
我使用旧版本的mongosync是支持非密码认证的mongos-mongos的全量和增量同步，新版本应该也是支持的吧？  
@gaodq

**Comment by elipoke** [comment]
@gaodq 
@baotiao 

[root@wsdevmgdb0420 mongosync_f650c8f]# ./mongosync --src_srv 192.168.4.25:10011 --src_user root --src_passwd 1234567 --src_auth_db admin --dst_srv 192.168.4.31:30001 --dst_user root --dst_passwd 12345678 --dst_auth_db admin --db crm --dst_db crm --bg_num 3             
[INFO ]         monogosync started, first set log level to INFO
[INFO ]         May 25 11:33:39 2017    [mongosync]     connect to srv_rsv: 192.168.4.25:10011 ok!
[INFO ]         May 25 11:33:39 2017    [mongosync]     srv: 192.168.4.25:10011, dbname: admin ok!
[INFO ]         May 25 11:33:39 2017    [mongosync]     connect to srv_rsv: 192.168.4.31:30001 ok!
[INFO ]         May 25 11:33:39 2017    [mongosync]     srv: 192.168.4.31:30001, dbname: admin ok!
[INFO ]         May 25 11:33:39 2017    [mongosync]     cloning db: crm ----> crm

[INFO ]         May 25 11:33:39 2017    [mongosync]     cloning crm.groupTest1 to crm.groupTest1
[INFO ]         May 25 11:33:39 2017    [mongosync]     cloning crm.groupTest1 indexes
[INFO ]         May 25 11:33:39 2017    [mongosync]     clone crm.groupTest1 indexes success, total 1objects

[WARN ]         exception occurs: 10278 dbclient error communicating with server: 192.168.4.25:10011, retry it
terminate called after throwing an instance of 'mongo::SocketException'
  what():  socket exception [FAILED_STATE] for 192.168.4.25:10011 (192.168.4.25) failed
Aborted (core dumped)
[root@wsdevmgdb0420 mongosync_f650c8f]#

**Comment by gaodq** [comment]
不支持mongos-mongos增量
看起来同步索引成功了，同步数据的时候失败了，是不是mongodb的配置有些问题？

**Comment by elipoke** [comment]
@gaodq 
集群是复制集+分片的形式，哪里会导致这个问题

**Comment by elipoke** [comment]
@gaodq 
不支持mongos-mongos增量
这比以前的老版本功能上退化了，以前老版本是支持的

**Comment by gaodq** [comment]
https://github.com/Qihoo360/mongosync/tree/mongos
还正在测试中，没确定发版

**Comment by tcrct** [comment]
是否支持全量同步后自动切换增量同步？

**Comment by gaodq** [comment]
@tcrct 支持

**Comment by tcrct** [comment]
@gaodq 分片同步到分片，分片同步到副本集应该也支持吧？

**Comment by gaodq** [comment]
你是说mongos的分片？这个支持，就是当做普通副本集处理。
