### ISSUE TITLE
macOS sierra下载下来make错误

### ISSUE THREAD

**Issue by merorin** [JacketWoo/mongosync#6]
hi,请问我按照wiki上的步骤下载下来后进行make,出现了17个warning和1个error,error如下：
mongosync.cc:587:3: error: no matching function for call to 'time'
                time(&cur);
                ^~~~
我试过直接下载编译好的二进制文件，但是无法运行，应该是编译环境不同的关系

那请问这个time相关的error要怎么处理呢？
[error.txt](https://github.com/Qihoo360/mongosync/files/1076545/error.txt)

**Comment by gaodq** [comment]
macOS上我们没有试过，这个错应该是库版本不一致导致的。https://github.com/Qihoo360/mongosync/blob/master/mongosync.cc#L539
这里cur变量定义为int64_t，应该是mac系统的编译器不自动转换这两种类型

**Comment by merorin** [comment]
谢谢解答~
