### ISSUE TITLE
目的副本集的master切换后，报Aborted (core dumped)错误后退出

### ISSUE THREAD

**Issue by Tim-Zhang** [JacketWoo/mongosync#7]
```./mongosync --src_srv 192.168.167.1:20000  --dst_srv localhost:20000  --db data --dst_db data --colls credentials,users --bg_num 10 --oplog 2>log3```

在使用以上语句进行`集合模式实时同步`时，目的副本集发生主从切换后，如果源端数据进行删除操作，`mongosync`就会挂掉，只有 `Aborted (core dumped)` 这一句报错。即使是源端数据进行插入操作，虽然`mongosync`不会挂掉，但是此操作并不能sync过来。

请问是mongosync不支持这种情况吗？

**Comment by Tim-Zhang** [comment]
如果不支持的话，有什么解决方案吗？

**Comment by gaodq** [comment]
mongodb版本目前仅支持到3.0，是不是版本的原因

**Comment by Tim-Zhang** [comment]
版本是3.2.3
